Elevator
OKTW-Network/Galaxy pull request #320
Opened 2020-08-10 14:39 UTC by asdf3601a

just 電梯

2020-08-10 14:40 UTC, jimchen5209 commented
- [ ] #287 Merged

2020-08-11 00:49 UTC, james58899 commented on src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerSneak_NetworkHandler.java
> +
多餘的空行

2020-08-11 00:50 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +
.

2020-08-11 00:53 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +import net.minecraft.client.options.ParticlesOption
多餘的import

2020-09-23 14:35 UTC, jimchen5209 requested changes
#287 function name change

2020-09-23 14:35 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +        if(CustomBlockUtil.positionIsBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, 1.0, 0.0)), BlockType.ELEVATOR)) {
```suggestion
        if(CustomBlockUtil.positionMatchesCustomBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, 1.0, 0.0)), BlockType.ELEVATOR)) {
```

2020-09-23 14:35 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +                if (CustomBlockUtil.positionIsBlock(event.player.serverWorld, BlockPos(position.add(0.0, i.toDouble(), 0.0)), BlockType.ELEVATOR)) {
```suggestion
                if (CustomBlockUtil.positionMatchesCustomBlock(event.player.serverWorld, BlockPos(position.add(0.0, i.toDouble(), 0.0)), BlockType.ELEVATOR)) {
```

2020-09-23 14:35 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +        if(CustomBlockUtil.positionIsBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, 1.0, 0.0)), BlockType.ELEVATOR)) {
```suggestion
        if(CustomBlockUtil.positionMatchesCustomBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, 1.0, 0.0)), BlockType.ELEVATOR)) {
```

2020-09-23 14:35 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +                if (CustomBlockUtil.positionIsBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, i.toDouble(), 0.0)), BlockType.ELEVATOR)) {
```suggestion
                if (CustomBlockUtil.positionMatchesCustomBlock(event.player.serverWorld, BlockPos(position.subtract(0.0, i.toDouble(), 0.0)), BlockType.ELEVATOR)) {
```

2020-10-05 07:24 UTC, james58899 commented
@asdf3601a

2020-11-10 15:57 UTC, james58899 commented
@asdf3601a

2020-11-11 15:41 UTC, bill96012 requested changes
- [ ] 電梯的檢查區間改從上或下的第二格開始，在第八格後結束
- [ ] 目標電梯的尋找範圍有誤，不應該從玩家的位置判斷，而是從電梯的位置開始
- [ ] 傳送時檢查(電梯自己)上面一格是空氣或水，否則不傳送
- [ ] 只傳送到上面一格是空氣或水的電梯

2020-11-14 06:12 UTC, james58899 requested changes

2020-11-14 06:12 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +                    event.player.serverWorld.getBlockState(BlockPos(position.add(0.0, 1.0, 0.0))).block == Blocks.AIR
不要get兩次同樣的東西

2020-11-15 05:52 UTC, james58899 requested changes
請重新排版與重新命名變數
以及避免多餘的座標重複加減

2020-11-15 05:52 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +                val nextElevatorPosition = event.player.serverWorld.getBlockState(BlockPos(position.add(0.0, i.toDouble() + 1.0, 0.0))).block
`nextElevatorPosition` 不是座標，請更正變數名稱

2020-11-15 05:52 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +        val currentElevatorPosition = event.player.serverWorld.getBlockState(BlockPos(position.add(0.0, 1.0, 0.0))).block
`currentElevatorPosition` 不是座標，請更正變數名稱

2020-11-15 05:52 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +                            nextElevatorPosition == Blocks.AIR
請刪除不必要的換行

2020-11-15 05:52 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +        val position = event.player.pos.subtract(0.0, 1.0, 0.0)
什麼的 `position` ？
是玩家還是電梯方塊？

2020-11-16 15:42 UTC, bill96012 approved these changes
Test passed

2020-11-16 15:52 UTC, james58899 approved these changes

2020-11-16 15:53 UTC, merged