Wrench spin
OKTW-Network/Galaxy pull request #323
Opened 2020-08-12 10:01 UTC by WoodManGitHub

為扳手加入旋轉方塊的功能

2020-08-12 11:50 UTC, jimchen5209 commented
- [ ] #287 Merged

2020-09-23 14:36 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
> +            blockState.contains(CHEST_TYPE) -> if (blockState.get(CHEST_TYPE) == ChestType.SINGLE) blockState.cycle(HORIZONTAL_FACING) else blockState
不能轉連起來的箱子？

2020-09-24 12:43 UTC, WoodManGitHub commented on src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
> +            blockState.contains(CHEST_TYPE) -> if (blockState.get(CHEST_TYPE) == ChestType.SINGLE) blockState.cycle(HORIZONTAL_FACING) else blockState
目前是這樣
要可以轉的話
我的想法是：
同面的時候把他分開，然後轉箱子，轉到同面的時候黏回去

2020-11-11 15:08 UTC, bill96012 requested changes
- [x] 必須在蹲下的時候才能改變方塊
- [x] 必須是該玩家可以破壞的方塊才能改變該方塊
- [x] 活塞應該要在沒有伸長的時候才能被改變
- [x] 如果戳到和箱子相同的面，讓面向相反
- [x] 陷阱箱要和箱子有一樣的邏輯
- [x] 終界箱要和箱子有一樣的旋轉和面向邏輯
- [x] 漏斗要和箱子有類似的旋轉和面向邏輯
- [ ] 樓梯在轉完一輪後改變 `half`
- [x] 砂輪在轉完一輪後改變 `face`
- [x] 告示牌、旗子、頭顱，應該要可以被旋轉
- [x] 床不應該被旋轉

2020-11-13 04:55 UTC, WoodManGitHub commented
改為成功使用扳手後才會揮手

2020-11-15 09:53 UTC, james58899 submitted a review, later dismissed
旋轉方向和順序應該統一(例如：東南西北上下/xyz)

以面向點擊的面為起點
若點擊的面無效以原始方向為起點
不是以方位旋轉的(頭顱、旗子、鎖鍊等)以目前方向為起點

箱子維持點擊兩個箱子之間合併，點擊合併的箱子分離

## 範例
#### 原始
![2020-11-15_17 41 50](https://user-images.githubusercontent.com/5798637/99181495-f62b1500-2769-11eb-8199-2425d5a57977.png)
#### 第一次旋轉
![2020-11-15_17 42 01](https://user-images.githubusercontent.com/5798637/99181537-1c50b500-276a-11eb-9ca9-b83d5f4ca1f7.png)
#### 第二次旋轉
![2020-11-15_17 42 13](https://user-images.githubusercontent.com/5798637/99181563-2f638500-276a-11eb-9e04-a9eaf0f92373.png)
#### 第三次旋轉
![2020-11-15_17 42 23](https://user-images.githubusercontent.com/5798637/99181574-37232980-276a-11eb-98f1-90edb37cf6cd.png)

2020-11-15 09:59 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
> +                if (blockState.block == REPEATER || blockState.block == COMPARATOR) {
能直接檢查是不是接受紅石訊號的方塊嗎？

2020-11-15 10:17 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
> +                if (blockState.block == REPEATER || blockState.block == COMPARATOR) {
那會有一堆方塊 match

2020-11-15 10:19 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
> +                if (blockState.block == REPEATER || blockState.block == COMPARATOR) {
聽起來沒問題，紅石就該被update

2020-11-16 22:22 UTC, bill96012 requested changes
- [x] 在玩家離開蹲下狀態或點擊其他方塊才重置面向調整

2020-11-17 03:19 UTC, bill96012 requested changes
確保從起始面相對的旋轉一圈後再進行上下的面向

有四個面向(東南西北)的方塊:
- 若以**東/南/西/北**面為起始面，相對旋轉 右->後->左:
  - (起始)東->南->西->北=>東->南->西->...
  - (起始)南->西->北->東=>南->西->北->...
  - (起始)西->北->東->南=>西->北->東->...
  - (起始)北->東->南->西=>北->東->南->...
- 若方塊有 `half` 或 `face`，相對旋轉 右->後->左 之後，改變其 `half` 或 `face`

有六個面向(東南西北上下)的方塊:
- 若以**東/南/西/北**為起始面，相對旋轉 右->後->左 之後，面向上再面向下:
  - (起始)東->南->西->北->上->下=>東->南->西->...
  - (起始)南->西->北->東->上->下=>南->西->北->...
  - (起始)西->北->東->南->上->下=>西->北->東->...
  - (起始)北->東->南->西->上->下=>北->東->南->...
- 若以上面為起始面，先面向下:
  - (起始)上->下->北->東->南->西=>上->下->北->東->南->...
- 若以下面為起始面，先面向上:
  - (起始)下->上->北->東->南->西=>下->上->北->東->南->...

2020-11-20 03:32 UTC, bill96012 reviewed
漏斗點上面的旋轉方式不統一
facing N E S 是轉一圈之後回到起始面才向下，但 facing W 是直接先向下才轉其他面

漏斗點上面旋轉的時候應該:
- (起始)北->東->南->西->下=>北->東->南
- (起始)東->南->西->北->下=>東->南->西
- (起始)南->西->北->東->下=>南->西->北
- (起始)西->北->東->南->下=>西->北->東
- (起始)下->北->東->南->西=>下->北->東

2020-11-25 12:20 UTC, bill96012 approved these changes
Test passed

2020-11-25 12:27 UTC, merged