Custom recipe & Easy Recipe
OKTW-Network/Galaxy pull request #335
Opened 2020-11-23 14:37 UTC by WoodManGitHub

Finish https://github.com/OKTW-Network/Galaxy/issues/329

2020-11-24 02:24 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/block/event/ElevatorEvents.kt
> +class ElevatorEvents {
喔之前放在 Main 然後名稱直接撞了

2020-11-24 02:42 UTC, james58899 requested changes

2020-11-24 02:42 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/recipe/utils/RecipeUtils.kt
> +        return inputItems.count() == 0
```suggestion
        return inputItems.isEmpty()
```

2020-11-24 02:42 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/recipe/utils/RecipeUtils.kt
> +        aBoolean: Boolean,
這是什麼？

2020-11-24 02:43 UTC, jimchen5209 commented on src/main/kotlin/one/oktw/galaxy/recipe/utils/RecipeUtils.kt
> +        aBoolean: Boolean,
我不知道
這是從 Minecraft 抄來的

2020-11-24 02:57 UTC, james58899 commented
Not ready to review

2020-12-11 07:53 UTC, bill96012 requested changes
1. 新增 warped_fungus_on_a_stick 的合成表:
    - 與 carrot_on_a_stick 的擺法相同，但 carrot 改為 warped_fungus
![擷取](https://user-images.githubusercontent.com/25405919/101877412-ec5dcb80-3bc8-11eb-91b5-ff440f6d427c.PNG)

2021-01-08 13:21 UTC, bill96012 submitted a review, later dismissed
Test passed

2021-08-28 10:13 UTC, bill96012 requested changes
- [x] 半磚合回全磚的合成表缺少了 1.17 的新方塊

    - 各種 `cut_copper` 和 `waxed` 過的版本，總共8種
    - `deepslate` 系列，總共4種
- [x] 讓清潔玻璃(片)的合成表可以清理不同數量的玻璃(片)
    - 不管清理幾個都消耗水桶的水
- [x] 新增中繼器合成表
    - 可以左右鏡像
    ![image](https://user-images.githubusercontent.com/25405919/131214403-0d135d95-c1fe-4860-8699-02f6b6990624.png)

2021-08-29 06:54 UTC, bill96012 approved these changes
Test passed

2021-08-29 16:19 UTC, asdf3601a approved these changes

2021-08-29 16:19 UTC, merged