Dispenser planting
OKTW-Network/Galaxy pull request #343
Opened 2020-11-30 12:59 UTC by WoodManGitHub

## Changes
加入發射器種植
- 小麥
- 馬鈴薯
- 胡蘿蔔
- 西瓜
- 南瓜
- 甜菜
- 甜莓根
- 樹苗
- 甘蔗
- 歌萊果
- 蘑菇

2020-12-07 10:03 UTC, bill96012 reviewed
1. 蘑菇和甜莓叢的放置音效的音調應該是0.8

2020-12-09 05:44 UTC, bill96012 reviewed
- [x] 可可豆
    - 只在發射器前方第二格的叢林木上放置
    ![unknown](https://user-images.githubusercontent.com/25405919/101589943-66088480-3a24-11eb-9b5a-4088f8f4c730.png)
    - 開口朝上或朝下的發射器不給種

2020-12-09 10:52 UTC, bill96012 reviewed
1. 可可豆也應該要可以種在其他型態的叢林木上:
    - jungle_wood
    - stripped_jungle_wood
2. 開口處朝上或下的發射器會把可可豆種在叢林木的上方或下方
![2020-12-09_18 46 32](https://user-images.githubusercontent.com/25405919/101620492-91ed2f80-3a4f-11eb-92b8-ec44c3acf65c.png)

2020-12-09 13:08 UTC, WoodManGitHub commented
- [ ] 修復甘蔗種植邏輯
- [ ] 修復可可豆種植邏輯
- [ ] 仙人掌種植

2020-12-10 01:53 UTC, bill96012 requested changes
1. 可可豆依然無法被種植在其他型態的叢林木上
2. 可可豆被錯誤的種植在叢林木上方
![2020-12-10_09 40 05](https://user-images.githubusercontent.com/25405919/101710942-7cb6e600-3acd-11eb-86ad-019273bf491f.png)

2020-12-10 11:29 UTC, bill96012 approved these changes
Test passed

2020-12-11 06:03 UTC, bill96012 requested changes
1. 開口朝上的發射器在種植仙人掌時，種植檢查的位置不正確
![2020-12-11_13 53 54](https://user-images.githubusercontent.com/25405919/101868507-72bde180-3bb8-11eb-8d2b-c2ef105cc987.png)
![2020-12-11_13 54 18](https://user-images.githubusercontent.com/25405919/101868514-76516880-3bb8-11eb-8061-34351fd2e3ce.png)

2021-01-07 15:34 UTC, bill96012 requested changes
1. 不要讓作物由下往上種
2. 海帶種植

2021-01-11 07:09 UTC, bill96012 requested changes
1. ~~海帶可以被種植在沒有落腳處的水中~~
    ![2021-01-11_15 03 19](https://user-images.githubusercontent.com/25405919/104153855-62e72680-541e-11eb-9b71-c3c51ee581c7.png)
2. ~~海帶應要可以由下往上種植~~
    ![2021-01-11_15 08 47](https://user-images.githubusercontent.com/25405919/104154086-ef91e480-541e-11eb-8508-fdaab23d23e9.png)

2021-01-11 07:42 UTC, bill96012 requested changes
1. 任何在 https://minecraft.gamepedia.com/Plants 的植物都要可以被種植

2021-01-11 09:27 UTC, WoodManGitHub commented
## 待加入
- [ ] 枯灌木
- [ ] 草
- [ ] 花
- [ ] 荷葉
- [ ] 海草
- [ ] 藤蔓
- [ ] 珊瑚
- [ ] 海鞘
- [ ] 地獄芽
- [ ] 緋紅蕈根
- [ ] 扭曲蕈根
- [ ] 扭曲藤
- [ ] 垂泣藤

2022-02-05 12:39 UTC, jimchen5209 commented
Ancient

2022-02-05 12:39 UTC, closed without merging