Rewrite elevator.
OKTW-Network/Galaxy pull request #350
Opened 2020-12-09 20:41 UTC by asdf3601a

效能改進(希望有)、更好看的Code以及新的判定機制。
現在電梯以及下一個電梯上方一格非實心方塊 -> 允許傳送 否則 不傳送

2020-12-10 01:54 UTC, james58899 requested changes

2020-12-10 01:54 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +            player.requestTeleport(pos.x.toDouble() + 0.5, pos.y.toDouble(), pos.z.toDouble() + 0.5)
要在伺服器執行序

2020-12-10 13:43 UTC, bill96012 requested changes
1. 沒辦法往下傳送

2020-12-11 03:34 UTC, james58899 requested changes

2020-12-11 05:18 UTC, bill96012 approved these changes
Test passed

2020-12-11 11:33 UTC, james58899 requested changes

2020-12-11 11:33 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
> +            player.requestTeleport(pos.x.toDouble() + 0.5, pos.y.toDouble(), pos.z.toDouble() + 0.5)
不要改變玩家的X/Z

2020-12-11 17:06 UTC, james58899 approved these changes

2020-12-11 17:10 UTC, merged