Fix #352
OKTW-Network/Galaxy pull request #353
Opened 2020-12-10 13:04 UTC by jimchen5209

## Changes
- Add marker to custom block entity (Fixes #352)

2020-12-10 13:24 UTC, bill96012 approved these changes
Test passed

2020-12-10 16:50 UTC, james58899 requested changes

2020-12-10 16:50 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/util/CustomBlockUtil.kt
> +        val entities = world.getEntitiesByType(EntityType.ARMOR_STAND) { it.scoreboardTags.contains("BLOCK") && it.blockPos == blockPos }
```suggestion
        val entities = world.getEntitiesByType(EntityType.ARMOR_STAND) { it.blockPos == blockPos && it.scoreboardTags.contains("BLOCK") }
```

2020-12-11 02:46 UTC, james58899 approved these changes

2020-12-11 02:46 UTC, merged