Trashcan
OKTW-Network/Galaxy pull request #401
Opened 2022-06-27 08:30 UTC by asdf3601a

2022-06-29 13:41 UTC, bill96012 reviewed
- [ ] 副手物品無法與方塊互動
- [ ] 蜂蜜罐無法以方塊互動的方式丟棄罐中的蜂蜜

2022-07-01 17:45 UTC, bill96012 reviewed
- [ ] 讓垃圾桶本身不發出聲音
- [ ] 添加下列物品的方塊互動
  - [ ] 蘑菇湯 -> 碗
  - [ ] 兔肉湯 -> 碗
  - [ ] 甜菜湯 -> 碗
  - [ ] 龍之吐息 -> 玻璃瓶

2022-07-02 18:01 UTC, bill96012 approved these changes
Test passed

2022-07-02 19:16 UTC, james58899 requested changes
請刪除所有多餘的操作

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/TrashcanBlock.kt
> +class TrashcanBlock(identifier: Identifier, private val modelItem: ItemStack) : CustomBlock(identifier, Blocks.BARRIER) {
直接繼承 `ModelCustomBlock`

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        return inventory.size
```suggestion
        return 1
```

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        inventory.clear()
```suggestion

```

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +    var inventory: DefaultedList<ItemStack> = DefaultedList.ofSize(1, ItemStack.EMPTY)
```suggestion
```

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        this.clear()
```suggestion
```

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        inventory[slot] = stack
```suggestion
```

2022-07-02 19:16 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        this.clear()
```suggestion
```

2022-07-10 08:59 UTC, bill96012 approved these changes
Test passed

2022-07-10 09:14 UTC, merged