Trashcan gui
OKTW-Network/Galaxy pull request #407
Opened 2022-07-12 08:32 UTC by asdf3601a

2022-07-12 15:50 UTC, james58899 requested changes

2022-07-12 15:50 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        } else player.squaredDistanceTo(pos.x.toDouble() + 0.5, pos.y.toDouble() + 0.5, pos.z.toDouble() + 0.5) <= 64.0
為什麼是64

2022-07-12 15:50 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +                val inv = FakeInventory(9 * 4)
```suggestion
                val inv = SimpleInventory(9 * 4)
```

2022-07-15 04:45 UTC, asdf3601a commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        } else player.squaredDistanceTo(pos.x.toDouble() + 0.5, pos.y.toDouble() + 0.5, pos.z.toDouble() + 0.5) <= 64.0
模仿 Minecraft LootableContainerBlockEntity.java 的行為

2022-07-16 02:35 UTC, asdf3601a commented
J個PR先等等GUI 👌👌

2022-07-17 16:10 UTC, james58899 commented on src/main/kotlin/one/oktw/galaxy/block/entity/TrashcanBlockEntity.kt
> +        if (!player.isSpectator) {
反轉這個if

2022-07-19 04:35 UTC, james58899 approved these changes

2022-07-19 10:48 UTC, bill96012 reviewed
1. 空手並蹲下戳方塊
    1. 關閉介面後又被開了一個新的垃圾桶介面
    2. 不會揮手手

2022-07-21 13:40 UTC, bill96012 approved these changes
Test passed

2022-07-22 02:30 UTC, merged